#!/bin/bash
export JAVA_HOME=/usr/lib/jvm/jdk-11

# Link to build folder
PROJECT="$(pwd)"
rm -f build
ln -s ~/SDL2-2.26.5/build build
cd build/net.lugocorp.minidungeons

# Fix broken include paths
FILES=$(ls app/jni/src | grep -e "\.[ch]pp$")
for FILE in $FILES
do
  sed -i -e 's/#include "dungeons\//#include "/g' "app/jni/src/$FILE"
done

# Update Android resources
rm -rf app/src/main/res
cp -r "$PROJECT/android-project/app/src/main/res" app/src/main/res

# Include SDL_ttf module and font asset
mkdir app/src/main/assets
ln -s ~/SDL2-2.26.5 app/jni/SDL
ln -s ~/SDL2_ttf-2.20.2 app/jni/SDL_ttf
sed -i -e 's/^LOCAL_SHARED_LIBRARIES.*/& SDL2_ttf/' app/jni/src/Android.mk
ln "$PROJECT/OpenSans-Regular.ttf" app/src/main/assets/OpenSans-Regular.ttf

# Initialize Gradle build
./gradlew installDebug